from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from html import escape

from .analyze import AnalysisResult


def write_json(out_dir: Path, result: AnalysisResult) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "report.json"
    path.write_text(json.dumps(asdict(result), ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def write_markdown(out_dir: Path, result: AnalysisResult) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "report.md"

    lines = []
    lines.append("# Log Analysis Report\n")

    lines.append("## Summary")
    lines.append(f"- Total lines: **{result.total_lines}**")
    lines.append(f"- Lines with timestamp parsed: **{result.parsed_with_timestamp}**")
    lines.append(f"- Unknown level lines: **{result.unknown_level}**")
    lines.append(f"- Empty lines: **{result.empty_lines}**")
    lines.append(f"- Error rate (ERROR+CRITICAL): **{result.error_rate:.4%}**")
    if result.time_start and result.time_end:
        lines.append(f"- Time range: **{result.time_start}** → **{result.time_end}**")
    lines.append("")

    lines.append("## Levels")
    for lvl, cnt in sorted(result.level_counts.items(), key=lambda x: (-x[1], x[0])):
        lines.append(f"- {lvl}: {cnt}")
    lines.append("")

    lines.append("## Top Modules")
    if result.top_modules:
        for mod, cnt in result.top_modules:
            lines.append(f"- {mod}: {cnt}")
    else:
        lines.append("- (no module info found)")
    lines.append("")

    lines.append("## Top Error Messages (normalized)")
    if result.top_error_messages:
        for msg, cnt in result.top_error_messages:
            lines.append(f"- ({cnt}x) {msg}")
    else:
        lines.append("- (no errors found)")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_html(out_dir: Path, result: AnalysisResult) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "report.html"

    def row(k: str, v: str) -> str:
        return f"<tr><th>{escape(k)}</th><td>{v}</td></tr>"

    time_range = (
        f"{escape(result.time_start)} → {escape(result.time_end)}"
        if result.time_start and result.time_end
        else "N/A"
    )

    levels_rows = "\n".join(
        f"<tr><td>{escape(lvl)}</td><td style='text-align:right'>{cnt}</td></tr>"
        for lvl, cnt in sorted(result.level_counts.items(), key=lambda x: (-x[1], x[0]))
    ) or "<tr><td colspan='2'>(no data)</td></tr>"

    modules_rows = "\n".join(
        f"<tr><td>{escape(mod)}</td><td style='text-align:right'>{cnt}</td></tr>"
        for mod, cnt in result.top_modules
    ) or "<tr><td colspan='2'>(no module info found)</td></tr>"

    errors_rows = "\n".join(
        f"<tr><td>{escape(msg)}</td><td style='text-align:right'>{cnt}</td></tr>"
        for msg, cnt in result.top_error_messages
    ) or "<tr><td colspan='2'>(no errors found)</td></tr>"

    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Log Analysis Report</title>
  <style>
    :root {{
      --bg: #0b0f14;
      --card: #121826;
      --text: #e6edf3;
      --muted: #9aa4b2;
      --border: #253045;
      --accent: #7aa2f7;
    }}
    body {{
      margin: 0;
      font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;
      background: var(--bg);
      color: var(--text);
      padding: 24px;
    }}
    .container {{ max-width: 1100px; margin: 0 auto; }}
    h1 {{ margin: 0 0 16px; font-size: 26px; }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      gap: 16px;
      align-items: start;
    }}
    .card {{
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 16px;
      box-shadow: 0 8px 24px rgba(0,0,0,0.35);
    }}
    .card h2 {{ margin: 0 0 10px; font-size: 16px; color: var(--accent); }}
    .muted {{ color: var(--muted); font-size: 13px; }}
    table {{
      width: 100%;
      border-collapse: collapse;
      font-size: 14px;
      overflow: hidden;
      border-radius: 10px;
    }}
    th, td {{
      border-bottom: 1px solid var(--border);
      padding: 8px 10px;
      vertical-align: top;
    }}
    th {{ text-align: left; color: var(--muted); width: 45%; }}
    tr:last-child th, tr:last-child td {{ border-bottom: none; }}
    code {{
      background: rgba(255,255,255,0.06);
      padding: 2px 6px;
      border-radius: 8px;
    }}
  </style>
</head>
<body>
  <div class="container">
    <h1>Log Analysis Report</h1>
    <div class="muted">Generated by <code>logan</code></div>

    <div class="grid" style="margin-top: 16px;">
      <div class="card">
        <h2>Summary</h2>
        <table>
          {row("Total lines", str(result.total_lines))}
          {row("Lines with timestamp parsed", str(result.parsed_with_timestamp))}
          {row("Unknown level lines", str(result.unknown_level))}
          {row("Empty lines", str(result.empty_lines))}
          {row("Error rate (ERROR+CRITICAL)", f"{result.error_rate:.4%}")}
          {row("Time range", escape(time_range))}
        </table>
      </div>

      <div class="card">
        <h2>Levels</h2>
        <table>
          <tr><th>Level</th><th style="text-align:right">Count</th></tr>
          {levels_rows}
        </table>
      </div>

      <div class="card">
        <h2>Top Modules</h2>
        <table>
          <tr><th>Module</th><th style="text-align:right">Count</th></tr>
          {modules_rows}
        </table>
      </div>

      <div class="card">
        <h2>Top Error Messages (normalized)</h2>
        <table>
          <tr><th>Message</th><th style="text-align:right">Count</th></tr>
          {errors_rows}
        </table>
        <div class="muted" style="margin-top:10px;">
          Tip: a normalizálás összevonja a hasonló hibákat (pl. ID-k, számok).
        </div>
      </div>
    </div>
  </div>
</body>
</html>
"""
    path.write_text(html, encoding="utf-8")
    return path
